// following guidance from https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html and https://datatracker.ietf.org/doc/html/rfc5789#section-2
export enum Method {
    options = "OPTIONS",
    get = "GET",
    head = "HEAD",
    post = "POST",
    put = "PUT",
    delete = "DELETE",
    trace = "TRACE",
    connect = "CONNECT",
    patch = "PATCH"
}

// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
export enum RequestHeaderField {
    wwwAuthentication = 'WWW-Authenticate',
    authorization = 'Authorization',
    proxyAuthenticate = 'Proxy-Authenticate',
    proxyAuthentication = 'Proxy-Authorization',
    age = 'Age',
    cacheControl = 'Cache-Control',
    clearSiteData = 'Clear-Site-Data',
    expires = 'Expires',
    pragma = "Pragma",
    warning = "Warning",
    acceptCH = 'Accept-CH',
    acceptCHLifetime = 'Accept-CH-Lifetime',
    earlyData = 'Early-Data',
    deviceMemory = 'Device-Memory',
    viewportWidth = 'Viewport-Width',
    width = 'Width',
    lastModified = 'Last-Modified',
    eTag = 'ETag',
    ifMatch = 'If-Match',
    ifNoneMatch = 'If-None-Match',
    ifModifiedSince = 'If-Modified-Since',
    ifUnmodifiedSince = 'If-Unmodified-Since',
    vary = 'Vary',
    accept = 'Accept',
    acceptCharset = 'Accept-Charset',
    acceptEncoding = 'Accept-Encoding',
    acceptLanguage = 'Accept-Language',
    expect = 'Expect',
    maxForwards = 'Max-Forwards',
    cookie = 'Cookie',
    setCookie = 'Set-Cookie',
    accessControlAllowOrigin = 'Access-Control-Allow-Origin',
    accessControlAllowCredentials = 'Access-Control-Allow-Credentials',
    accessControlAllowHeaders = 'Access-Control-Allow-Headers',
    accessControlAllowMethods = 'Access-Control-Allow-Methods',
    accessControlExposeHeaders = 'Access-Control-Expose-Headers',
    accessControlMaxAge = 'Access-Control-Max-Age',
    accessControlRequestHeaders = 'Access-Control-Request-Headers',
    accessControlRequestMethod = 'Access-Control-Request-Method',
    origin = 'Origin',
    timingAllowOrigin = 'Timing-Allow-Origin',
    dnt = 'DNT',
    tk = 'Tk',
    contentDisposition = 'Content-Disposition',
    contentLength = 'Content-Length',
    contentType = 'Content-Type',
    contentEncoding = 'Content-Encoding',
    contentLanguage = 'Content-Language',
    contentLocation = 'Content-Location',
    forwarded = 'Forwarded',
    via = 'Via',
    location = 'Location',
    from = 'From',
    host = 'Host',
    referer = 'Referer',
    referrerPolicy = 'Referrer-Policy',
    userAgent = 'User-Agent'
}

export enum ResponseHeaderField {
    allow = 'Allow',
    date = 'Date',
    expires = 'Expires',
    cacheControl = "Cache-Control",
    contentType = "Content-Type",
    contentLength = "Content-Length",
    p3p = "P3P",
    server = "Server",
    xXssProtection = "X-XSS-Protection",
    xFrameOptions = "X-Frame-Options",
    setCookie = "Set-Cookie",
    connection = "Connection",
    transferEncoding = "Transfer-Encoding"
}

// https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types
// https://en.wikipedia.org/wiki/Media_type
export enum MIMEType {
    json = "application/json",
    octet = "application/octet-stream",
    sql = "application/sql",
    plain = "text/plain",
    css = "text/css",
    csv = "text/csv",
    html = "text/html",
    xml = "text/xml",
    xmlApp = "application/xml",
    js ="text/javascript",
    jsApp = "application/javascript",
    ecma = "application/ecmascript",
    ecmaApp = "text/ecmascript",
    graphql = "application/graphql",
    ldJson = "application/ld+json",
    wwwFormUrlEncoded = "application/x-www-form-urlencoded",
}